name: Guard Main Content

on:
  pull_request:
    branches: ["main"]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for forbidden files on main
        run: |
          bash scripts/guard-main.sh main
