name: Upgrade Runner

on:
  workflow_dispatch: {}

permissions:
  contents: write
  actions: write

jobs:
  run-upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: List scripts
        run: ls -la scripts || true

      - name: Make scripts executable
        run: chmod +x scripts/*.sh || true

      - name: Run pre-upgrade (install)
        env:
          GIT_CHECKPOINT_POLICY: tag
        run: |
          set -euo pipefail
          ./scripts/upgrade-checkpoint.sh pre-upgrade

      - name: Upgrade firebase
        env:
          GIT_CHECKPOINT_POLICY: tag
        run: |
          set -euo pipefail
          ./scripts/upgrade-checkpoint.sh upgrade-firebase
          ./scripts/upgrade-checkpoint.sh install-after-firebase

      - name: Typecheck
        env:
          GIT_CHECKPOINT_POLICY: tag
        run: ./scripts/upgrade-checkpoint.sh typecheck

      - name: Build
        env:
          GIT_CHECKPOINT_POLICY: tag
        run: ./scripts/upgrade-checkpoint.sh build

      - name: Test
        env:
          GIT_CHECKPOINT_POLICY: tag
        run: ./scripts/upgrade-checkpoint.sh test

      - name: Push tags back
        if: always()
        run: |
          git push origin --tags || echo "push tags failed"
